[build]
command = "npm run build" 
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/proxy/*"
  to = "https://pokeapi.co/:splat"
  status = 200
  force = true
